version: '3.4'

services:
  
  plenny-oracle:
    container_name: plenny-oracle
    image: 0xidm/plenny-oracle:latest
    restart: unless-stopped
    volumes:
      - /usr/local/src/plenny-oracle/config:/home/plenny/.plenny-oracle
    ports:
      - "3001:3001" # Lightning Oracle (TCP)
    command:
      - /opt/PlennyDLSP_Linux_x86_64/PlennyDLSP
